CREATE TABLE IF NOT EXISTS inv_items (

    item_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    item_code VARCHAR(255),
    item_name VARCHAR(255),
    quantity DECIMAL

)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS inv_skus (

    sku_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    item_id BIGINT,
    barcode VARCHAR(255)

)ENGINE=INNODB DEFAULT CHARSET=UTF8;

