spring:
  application:
    name: spring-data-rest
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:7000/spring-data-rest
    username: DB_USERNAME
    password: DB_PASSWORD
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true
    show-sql: true
    
server:
  port: 7100
